spring:
  application:
    name: ebooking
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ebooking_db}
    username: ${SPRING_DATASOURCE_USERNAME:jerry}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true

jwt:
  secret: cle_secret@springboot.com
