spring:
  application:
    name: ebooking
  datasource:
    url: jdbc:postgresql://localhost:5432/ebooking_db
    username: jerry
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true

jwt:
  secret: cle_secret@springboot.com
